baseURL = 'https://www.webdevmentor.info/'
languageCode = 'de-de'
title = 'WebDevMentor'
theme = 'ananke'
[params]
    description = 'Lerne Webentwicklung mit Fokus auf PHP, Docker und modernen Workflows. Mentorings und Tipps f√ºr Einsteiger und Fortgeschrittene.'
[sitemap]
    changeFreq = 'monthly'
enableRobotsTXT = false
disableKinds = ["rss"]
[outputs]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomy = []
    term = []
    page = ["HTML"]
    rss = []
[markup.goldmark.renderer]
    unsafe = true
