baseURL = 'https://www.webdevmentor.info/'
languageCode = 'de-de'
title = 'WebDevMentor'
theme = 'ananke'
[sitemap]
    changeFreq = 'monthly'
enableRobotsTXT = false
[params]
[markup.goldmark.renderer]
    unsafe = true
