baseURL = 'https://www.webdevmentor.info/'
languageCode = 'de-de'
title = 'WebDevMentor'
theme = 'ananke'
[sitemap]
    changeFreq = 'monthly'
enableRobotsTXT = false
disableKinds = ["rss"]
[outputs]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomy = []
    term = []
    page = ["HTML"]
    rss = []
[markup.goldmark.renderer]
    unsafe = true
